name: sunotes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
   
  build_runner: ^2.4.13
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
